# Generated by Django 4.2.7 on 2025-05-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField()),
                ('id_atleta1', models.IntegerField()),
                ('id_atleta2', models.IntegerField()),
                ('flag_finalizado', models.IntegerField()),
                ('round', models.CharField(max_length=150)),
                ('id_atleta_ganhador', models.IntegerField(blank=True, null=True)),
                ('sportAlternateName', models.CharField(max_length=150)),
                ('weightCategoryName', models.CharField(max_length=150)),
                ('audienceName', models.CharField(max_length=150)),
                ('id_classe_peso', models.IntegerField()),
                ('atleta1_flag_injured', models.IntegerField()),
                ('atleta1_flag_seeded', models.IntegerField()),
                ('atleta1_draw_rank', models.CharField(max_length=10)),
                ('atleta1_RobinRank', models.CharField(max_length=10)),
                ('atleta2_flag_injured', models.IntegerField()),
                ('atleta2_flag_seeded', models.IntegerField()),
                ('atleta2_draw_rank', models.CharField(max_length=10)),
                ('atleta2_RobinRank', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=30)),
                ('tipo_vitoria', models.CharField(max_length=10)),
                ('atleta1_ranking_point', models.IntegerField()),
                ('atleta2_ranking_point', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('tapete', models.CharField(max_length=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
    ]
