# Generated by Django 4.2.7 on 2025-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_luta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luta',
            name='atleta1_flag_injured',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
