# Generated by Django 4.2.7 on 2025-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_luta_atleta1_flag_injured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luta',
            name='atleta1_RobinRank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta1_draw_rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta1_flag_injured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta1_flag_seeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta1_ranking_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_RobinRank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_draw_rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_flag_injured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_flag_seeded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_ranking_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='flag_finalizado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='luta',
            name='id_classe_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='resultado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='tipo_vitoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
