# Generated by Django 4.2.7 on 2025-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_luta_atleta1_robinrank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luta',
            name='atleta1_flag_injured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta1_flag_seeded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_flag_injured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='atleta2_flag_seeded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luta',
            name='flag_finalizado',
            field=models.IntegerField(),
        ),
    ]
