# Generated by Django 4.2.7 on 2025-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosSge',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_sge', models.IntegerField()),
                ('id_arena', models.CharField(max_length=100)),
                ('local', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('id_tipo', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('escopo', models.CharField(blank=True, max_length=50, null=True)),
                ('audienceName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
