# Generated by Django 4.2.7 on 2025-08-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_eventossge'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventossge',
            name='api_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventossge',
            name='client_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventossge',
            name='client_secret',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
