# Generated by Django 4.2.7 on 2025-08-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_eventossge_api_key_eventossge_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsArena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=150, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=150, null=True)),
                ('api_key', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_maquina', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventossge',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='eventossge',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='eventossge',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='eventossge',
            name='id_arena',
        ),
        migrations.AlterField(
            model_name='eventossge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventossge',
            name='id_sge',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='EventosArena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_arena', models.CharField(max_length=100, unique=True)),
                ('nome_evento', models.CharField(max_length=100)),
                ('isTeamEvent', models.BooleanField()),
                ('isBeachWrestlingTournament', models.BooleanField()),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='polls.credentialsarena')),
                ('eventos_sge', models.ManyToManyField(related_name='eventos_arena', to='polls.eventossge')),
            ],
        ),
    ]
