# Generated by Django 4.2.7 on 2025-08-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_credentialsarena_remove_eventossge_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosarena',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
