# Generated by Django 4.2.7 on 2025-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_eventosarena_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosarena',
            name='ano',
        ),
        migrations.AddField(
            model_name='eventossge',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
