# Generated by Django 4.2.7 on 2025-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_eventosarena_ano_eventossge_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosarena',
            name='audienceName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
